// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package openrtb

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson344736e9DecodeGithubComBsmOpenrtb(in *jlexer.Lexer, out *Content) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "episode":
			out.Episode = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "series":
			out.Series = string(in.String())
		case "season":
			out.Season = string(in.String())
		case "artist":
			out.Artist = string(in.String())
		case "genre":
			out.Genre = string(in.String())
		case "album":
			out.Album = string(in.String())
		case "isrc":
			out.ISRC = string(in.String())
		case "producer":
			if in.IsNull() {
				in.Skip()
				out.Producer = nil
			} else {
				if out.Producer == nil {
					out.Producer = new(Producer)
				}
				easyjson344736e9DecodeGithubComBsmOpenrtb1(in, &*out.Producer)
			}
		case "url":
			out.URL = string(in.String())
		case "cat":
			if in.IsNull() {
				in.Skip()
				out.Cat = nil
			} else {
				in.Delim('[')
				if out.Cat == nil {
					if !in.IsDelim(']') {
						out.Cat = make([]string, 0, 4)
					} else {
						out.Cat = []string{}
					}
				} else {
					out.Cat = (out.Cat)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Cat = append(out.Cat, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "prodq":
			out.ProdQuality = int(in.Int())
		case "videoquality":
			out.VideoQuality = int(in.Int())
		case "context":
			out.Context = int(in.Int())
		case "contentrating":
			out.ContentRating = string(in.String())
		case "userrating":
			out.UserRating = string(in.String())
		case "qagmediarating":
			out.QAGMediaRating = int(in.Int())
		case "keywords":
			out.Keywords = string(in.String())
		case "livestream":
			out.LiveStream = int(in.Int())
		case "sourcerelationship":
			out.SourceRelationship = int(in.Int())
		case "len":
			out.Len = int(in.Int())
		case "language":
			out.Language = string(in.String())
		case "embeddable":
			out.Embeddable = int(in.Int())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Data, 0, 1)
					} else {
						out.Data = []Data{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v2 Data
					(v2).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ext":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Ext).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson344736e9EncodeGithubComBsmOpenrtb(out *jwriter.Writer, in Content) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"id\":")
		out.String(string(in.ID))
	}
	if in.Episode != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"episode\":")
		out.Int(int(in.Episode))
	}
	if in.Title != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"title\":")
		out.String(string(in.Title))
	}
	if in.Series != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"series\":")
		out.String(string(in.Series))
	}
	if in.Season != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"season\":")
		out.String(string(in.Season))
	}
	if in.Artist != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"artist\":")
		out.String(string(in.Artist))
	}
	if in.Genre != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"genre\":")
		out.String(string(in.Genre))
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"album\":")
	out.String(string(in.Album))
	if in.ISRC != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"isrc\":")
		out.String(string(in.ISRC))
	}
	if in.Producer != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"producer\":")
		if in.Producer == nil {
			out.RawString("null")
		} else {
			easyjson344736e9EncodeGithubComBsmOpenrtb1(out, *in.Producer)
		}
	}
	if in.URL != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"url\":")
		out.String(string(in.URL))
	}
	if len(in.Cat) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"cat\":")
		if in.Cat == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Cat {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	if in.ProdQuality != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"prodq\":")
		out.Int(int(in.ProdQuality))
	}
	if in.VideoQuality != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"videoquality\":")
		out.Int(int(in.VideoQuality))
	}
	if in.Context != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"context\":")
		out.Int(int(in.Context))
	}
	if in.ContentRating != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"contentrating\":")
		out.String(string(in.ContentRating))
	}
	if in.UserRating != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"userrating\":")
		out.String(string(in.UserRating))
	}
	if in.QAGMediaRating != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"qagmediarating\":")
		out.Int(int(in.QAGMediaRating))
	}
	if in.Keywords != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"keywords\":")
		out.String(string(in.Keywords))
	}
	if in.LiveStream != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"livestream\":")
		out.Int(int(in.LiveStream))
	}
	if in.SourceRelationship != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"sourcerelationship\":")
		out.Int(int(in.SourceRelationship))
	}
	if in.Len != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"len\":")
		out.Int(int(in.Len))
	}
	if in.Language != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"language\":")
		out.String(string(in.Language))
	}
	if in.Embeddable != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"embeddable\":")
		out.Int(int(in.Embeddable))
	}
	if len(in.Data) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"data\":")
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Data {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Ext) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"ext\":")
		out.Raw((in.Ext).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Content) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson344736e9EncodeGithubComBsmOpenrtb(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Content) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson344736e9EncodeGithubComBsmOpenrtb(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Content) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson344736e9DecodeGithubComBsmOpenrtb(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Content) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson344736e9DecodeGithubComBsmOpenrtb(l, v)
}
func easyjson344736e9DecodeGithubComBsmOpenrtb1(in *jlexer.Lexer, out *Producer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "cat":
			if in.IsNull() {
				in.Skip()
				out.Cat = nil
			} else {
				in.Delim('[')
				if out.Cat == nil {
					if !in.IsDelim(']') {
						out.Cat = make([]string, 0, 4)
					} else {
						out.Cat = []string{}
					}
				} else {
					out.Cat = (out.Cat)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					v7 = string(in.String())
					out.Cat = append(out.Cat, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "domain":
			out.Domain = string(in.String())
		case "ext":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Ext).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson344736e9EncodeGithubComBsmOpenrtb1(out *jwriter.Writer, in Producer) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"id\":")
		out.String(string(in.ID))
	}
	if in.Name != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"name\":")
		out.String(string(in.Name))
	}
	if len(in.Cat) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"cat\":")
		if in.Cat == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Cat {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	if in.Domain != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"domain\":")
		out.String(string(in.Domain))
	}
	if len(in.Ext) != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"ext\":")
		out.Raw((in.Ext).MarshalJSON())
	}
	out.RawByte('}')
}
